export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_USER = "FETCH_USER";
export const ADD_PATH_TOOGLE_MODAL = "ADD_PATH_TOOGLE_MODAL";
export const ADD_MARKER = "ADD_MARKER";
export const ADD_DISTANCE = "ADD_DISTANCE";
export const FETCH_TRAVELS = "FETCH_TRAVELS";
export const SELECT_TRAVEL = "SELECT_TRAVEL";