
export const ADD_PATH_TOOGLE_MODAL = "ADD_PATH_TOOGLE_MODAL";
export const ADD_MARKER = "ADD_MARKER";
export const ADD_DISTANCE = "ADD_DISTANCE";
export const FETCH_TRAVELS = "FETCH_TRAVELS";
export const SELECT_TRAVEL = "SELECT_TRAVEL";
export const ADD_MARKER_REF = "ADD_MARKER_REF";
export const FILTER_TRAVELS = "FILTER_TRAVELS";
export const DELETE_TRAVEL = "DELETE_TRAVEL";